package data_writer;

import lombok.SneakyThrows;

import java.io.FileWriter;

/**
 * @author Nouran Ahmed
 * <p>This class is for writing any kind of test-Data (mainly Faker_Generated data, but can
 * write data from properties files to a text file if needed, or maybe from json to Properties file, etc.)</p>
 */
public class TestData_Writer {

    private static boolean isFileCleared = false;

    /**
     * Method to clear the file only once at the start of each run
     * @param file_Path the name of the path to which the condition of clearness will be applied
     * */
    @SneakyThrows
    public static void clearFile(String file_Path) {
        if (!isFileCleared) {
            new FileWriter(file_Path, false).close();
            isFileCleared = true;
        }
    }

    /**
     * Reads test data generated by Faker class in some TCs
     * @param variable_Name the name of the variable I used in TC that stores the fake data
     * @param data the dummy fake data generated by Faker class
     * @return the dummy data to be stored in that variable that will be used in the test_steps
     */
    @SneakyThrows
    public static String write_Generated_Data(String test_Data_File_Path, String variable_Name, String data)
    {
        clearFile(test_Data_File_Path);

        FileWriter fw = new FileWriter(test_Data_File_Path,true);
        fw.write(variable_Name + " : " + data);
        fw.write("\n");
        fw.flush();
        fw.close();
        return data;
    }

}
